# Generated by Django 2.1 on 2018-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=128)),
                ('playlistURI', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('uri', models.CharField(max_length=32)),
                ('artist', models.CharField(max_length=32)),
                ('album_img', models.CharField(max_length=64)),
            ],
        ),
    ]
