# Generated by Django 2.1 on 2018-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='playlistURI',
        ),
        migrations.AddField(
            model_name='session',
            name='playlist_uri',
            field=models.CharField(default='bro idk', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='sid',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='track',
            name='session_id',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='error: unnamed', max_length=64),
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(default='no token', max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_img',
            field=models.CharField(default='no album', max_length=64),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='Darude', max_length=32),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(default='Sandstorm', max_length=64),
        ),
        migrations.AlterField(
            model_name='track',
            name='uri',
            field=models.CharField(default='spotify:no_track', max_length=32),
        ),
    ]
