# Generated by Django 2.1 on 2018-09-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_auto_20180827_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='playlist_uri',
            field=models.CharField(default='bro idk', max_length=22),
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(default='no token', max_length=207),
        ),
    ]
