# Generated by Django 2.0.3 on 2018-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0003_auto_20180904_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='playlist_uri',
            new_name='pid',
        ),
    ]
